const DATABASE_NAME = '@todoify'

const COLLECTION_AUTH_TOKEN = `${DATABASE_NAME}:auth-token`
const COLLECTION_USERNAME = `${DATABASE_NAME}:username`
const COLLECTION_TASKS = `${DATABASE_NAME}:tasks`
const COLLECTION_SECTIONS = `${DATABASE_NAME}:sections`

export {
    COLLECTION_AUTH_TOKEN,
    COLLECTION_USERNAME,
    COLLECTION_TASKS,
    COLLECTION_SECTIONS
}
